name: Update Portfolio

on:
  schedule:
    # Run once at 9:30am EST (14:30 UTC)
    - cron: "30 14 * * 1-5"
    # Then run hourly on the hour until 4pm EST (21:00 UTC)
    - cron: "0 15-21 * * 1-5"

  workflow_dispatch:  # allow manual runs

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_portfolio.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Update portfolio [skip ci]" || echo "No changes to commit"
          git push